#!/usr/bin/env bash
if [ "$2" == "clone" ]; then
  git clone https://github.com/lucasapoena/docker-dev-magento2.git $1 && cd $1;
fi

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

sudo chmod -R u+x ./*

docker image pull lucasapoena/docker-dev-magento2:php7.1-apache

git checkout -f master;
sed -i '' -e "s/<project_name>/$1/g" docker-compose.yml;

if [ ! -e src/index.php ]; then
  echo "<?php phpinfo();" > src/index.php;
fi

chmod -R 777 src

bash start